Importing the Dependencies

In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

PIMA Diabetes Dataset

In [36]:
# loading the diabetes dataset to a pandas DataFrame
ks_dataset = pd.read_csv('kidney-stone-dataset.csv') 
ks_dataset

     gravity        ph  osmo       cond  urea      calc  target
0   1.021000  4.910000   725  14.000000   443  2.450000       0
1   1.017000  5.740000   577  20.000000   296  4.490000       0
2   1.008000  7.200000   321  14.900000   101  2.360000       0
3   1.011000  5.510000   408  12.600000   224  2.150000       0
4   1.005000  6.520000   187   7.500000    91  1.160000       0
..       ...       ...   ...        ...   ...       ...     ...
85  1.021452  5.556081   756  24.241481   367  7.669120       1
86  1.016501  6.900257   549  20.549790   204  5.775256       1
87  1.032754  5.443491  1085  23.188653   576  8.664169       1
88  1.023870  5.106433   325  12.124689    50  0.781620       1
89  1.013723  6.308943   472  16.907792   174  2.556405       1

[90 rows x 7 columns]

In [37]:
# printing the first 5 rows of the dataset
ks_dataset.head()

   gravity    ph  osmo  cond  urea  calc  target
0    1.021  4.91   725  14.0   443  2.45       0
1    1.017  5.74   577  20.0   296  4.49       0
2    1.008  7.20   321  14.9   101  2.36       0
3    1.011  5.51   408  12.6   224  2.15       0
4    1.005  6.52   187   7.5    91  1.16       0

In [38]:
ks_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   gravity  90 non-null     float64
 1   ph       90 non-null     float64
 2   osmo     90 non-null     int64
 3   cond     90 non-null     float64
 4   urea     90 non-null     int64
 5   calc     90 non-null     float64
 6   target   90 non-null     int64
dtypes: float64(4), int64(3)
memory usage: 5.1 KB

In [39]:
# number of rows and Columns in this dataset
ks_dataset.shape

(90, 7)

In [40]:
# getting the statistical measures of the data
ks_dataset.describe()

,gravity,ph,osmo,cond,urea,calc,target
count,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000
mean,1.017952,6.036651,602.333333,20.621687,258.200000,4.017788,0.500000
std,0.006780,0.711801,238.459805,7.654448,135.381127,3.016273,0.502801
min,1.005000,4.760000,187.000000,5.100000,10.000000,0.170000,0.000000
25%,1.012258,5.536520,411.500000,14.150000,148.250000,1.412500,0.000000
50%,1.018000,5.936247,572.000000,21.177172,231.500000,3.230000,0.500000
75%,1.023000,6.490000,778.000000,26.075000,366.250000,5.965127,1.000000
max,1.034000,7.940000,1236.000000,38.000000,620.000000,13.000000,1.000000

In [41]:
ks_dataset['target'].value_counts()

target
0    45
1    45
Name: count, dtype: int64

0 --> Non-KS

1 --> KS

In [43]:
ks_dataset.groupby('target').mean()

         gravity        ph        osmo       cond        urea      calc
target
0       1.015489  6.098667  565.288889  20.404444  237.111111  2.624889
1       1.020415  5.974635  639.377778  20.838930  279.288889  5.410687

In [44]:
# separating the data and labels
X = ks_dataset.drop(columns = 'target', axis=1)
Y = ks_dataset['target']

In [45]:
print(X)

     gravity        ph  osmo       cond  urea      calc
0   1.021000  4.910000   725  14.000000   443  2.450000
1   1.017000  5.740000   577  20.000000   296  4.490000
2   1.008000  7.200000   321  14.900000   101  2.360000
3   1.011000  5.510000   408  12.600000   224  2.150000
4   1.005000  6.520000   187   7.500000    91  1.160000
..       ...       ...   ...        ...   ...       ...
85  1.021452  5.556081   756  24.241481   367  7.669120
86  1.016501  6.900257   549  20.549790   204  5.775256
87  1.032754  5.443491  1085  23.188653   576  8.664169
88  1.023870  5.106433   325  12.124689    50  0.781620
89  1.013723  6.308943   472  16.907792   174  2.556405

[90 rows x 6 columns]

In [46]:
print(Y)

0     0
1     0
2     0
3     0
4     0
     ..
85    1
86    1
87    1
88    1
89    1
Name: target, Length: 90, dtype: int64

Train Test Split

In [48]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.15, stratify=Y, random_state=2)

In [49]:
print(X.shape, X_train.shape, X_test.shape)

(90, 6) (76, 6) (14, 6)

Training the Model

## Model :

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [69]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 5)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=5)

In [70]:
y_pred = classifier.predict(X_test)

In [71]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[5 2]
 [0 7]]

0.8571428571428571

In [72]:
a = sc.fit_transform([[1.021,4.91,725,14.0,443,2.45]])

print(classifier.predict(a))

[0]

In [78]:
input_data = (1.021,4.91,725,14.0,443,2.45)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not Kidney Stone')
else:
  print('The person has Kidney Stone')

[1]
The person has Kidney Stone

Saving the trained model

In [84]:
import pickle

In [85]:
filename = 'ks_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [87]:
# loading the saved model
loaded_model = pickle.load(open('ks_model.sav', 'rb'))

In [95]:
input_data = sc.fit_transform([[1.021,4.91,725,14.0,443,2.45]])

# changing the input_data to numpy array
# input_data_as_numpy_array = np.asarray(input_data)

# # reshape the array as we are predicting for one instance
# input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data)
print(prediction)

if (prediction[0] == 0):
  print('The person has not Kidney Stone')
else:
  print('The person has Kidney Stone')

[0]
The person has not Kidney Stone

In [ ]:
for column in X.columns:
  print(column)