Importing the Dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

PIMA Diabetes Dataset

In [4]:
# loading the diabetes dataset to a pandas DataFrame
stroke_dataset = pd.read_csv('stroke_data.csv') 
stroke_dataset

,sex,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1.0,63.0,0,1,1,4,1,228.69,36.6,1,1
1,1.0,42.0,0,1,1,4,0,105.92,32.5,0,1
2,0.0,61.0,0,0,1,4,1,171.23,34.4,1,1
3,1.0,41.0,1,0,1,3,0,174.12,24.0,0,1
4,1.0,85.0,0,0,1,4,1,186.21,29.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
40905,1.0,38.0,0,0,0,4,1,120.94,29.7,1,0
40906,0.0,53.0,0,0,1,4,0,77.66,40.8,0,0
40907,1.0,32.0,0,0,1,2,0,231.95,33.2,0,0
40908,1.0,42.0,0,0,1,3,0,216.38,34.5,0,0
40909,1.0,35.0,0,0,0,4,0,95.01,28.0,0,0

In [5]:
stroke_dataset.dropna(inplace=True)

In [6]:
stroke_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40907 entries, 0 to 40909
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sex                40907 non-null  float64
 1   age                40907 non-null  float64
 2   hypertension       40907 non-null  int64
 3   heart_disease      40907 non-null  int64
 4   ever_married       40907 non-null  int64
 5   work_type          40907 non-null  int64
 6   Residence_type     40907 non-null  int64
 7   avg_glucose_level  40907 non-null  float64
 8   bmi                40907 non-null  float64
 9   smoking_status     40907 non-null  int64
 10  stroke             40907 non-null  int64
dtypes: float64(4), int64(7)
memory usage: 3.7 MB

In [7]:
# printing the first 5 rows of the dataset
stroke_dataset.head()

,sex,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1.0,63.0,0,1,1,4,1,228.69,36.6,1,1
1,1.0,42.0,0,1,1,4,0,105.92,32.5,0,1
2,0.0,61.0,0,0,1,4,1,171.23,34.4,1,1
3,1.0,41.0,1,0,1,3,0,174.12,24.0,0,1
4,1.0,85.0,0,0,1,4,1,186.21,29.0,1,1

In [8]:
# number of rows and Columns in this dataset
stroke_dataset.shape

(40907, 11)

In [9]:
# getting the statistical measures of the data
stroke_dataset.describe()

,sex,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
count,40907.000000,40907.000000,40907.000000,40907.000000,40907.000000,40907.000000,40907.000000,40907.000000,40907.000000,40907.000000,40907.000000
mean,0.555162,51.327303,0.213851,0.127729,0.821326,3.461095,0.514851,122.079679,30.406488,0.488572,0.500159
std,0.496954,21.624171,0.410028,0.333792,0.383083,0.780934,0.499786,57.561951,6.835305,0.499875,0.500006
min,0.000000,-9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,55.120000,11.500000,0.000000,0.000000
25%,0.000000,35.000000,0.000000,0.000000,1.000000,3.000000,0.000000,78.750000,25.900000,0.000000,0.000000
50%,1.000000,52.000000,0.000000,0.000000,1.000000,4.000000,1.000000,97.920000,29.400000,0.000000,1.000000
75%,1.000000,68.000000,0.000000,0.000000,1.000000,4.000000,1.000000,167.590000,34.100000,1.000000,1.000000
max,1.000000,103.000000,1.000000,1.000000,1.000000,4.000000,1.000000,271.740000,92.000000,1.000000,1.000000

In [10]:
stroke_dataset['stroke'].value_counts()

stroke
1    20460
0    20447
Name: count, dtype: int64

0 --> Non-stroke

1 --> stroke

In [12]:
stroke_dataset.groupby('stroke').mean()

,sex,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
stroke,,,,,,,,,,
0,0.610358,50.061134,0.108378,0.052966,0.751700,3.440358,0.508974,106.797871,30.281313,0.454345
1,0.500000,52.592669,0.319257,0.202444,0.890909,3.481818,0.520723,137.351777,30.531584,0.522776

In [13]:
stroke_input = stroke_dataset.sample(20000)

In [14]:
stroke_input

,sex,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
21489,0.0,25.0,0,0,1,4,0,76.55,29.0,1,0
15231,0.0,65.0,0,0,1,3,0,104.12,23.5,0,1
24149,1.0,22.0,0,0,1,4,0,237.15,27.7,0,0
36098,1.0,22.0,0,0,1,3,1,234.06,33.7,0,0
6350,1.0,52.0,0,0,1,3,1,99.33,33.7,0,1
...,...,...,...,...,...,...,...,...,...,...,...
9810,0.0,57.0,0,0,1,4,1,60.91,29.9,0,1
33918,1.0,16.0,0,0,1,4,1,102.77,35.8,1,0
30678,1.0,13.0,0,0,1,3,1,68.61,31.9,0,0
18646,1.0,42.0,0,0,1,3,0,90.00,32.0,0,1
21453,1.0,69.0,0,0,1,4,1,83.41,29.9,0,0

In [15]:
stroke_input['stroke'].value_counts()

stroke
1    10034
0     9966
Name: count, dtype: int64

In [16]:
# separating the data and labels
X = stroke_input.drop(columns = 'stroke', axis=1)
Y = stroke_input['stroke']

In [17]:
print(X)

       sex   age  hypertension  heart_disease  ever_married  work_type  \
21489  0.0  25.0             0              0             1          4
15231  0.0  65.0             0              0             1          3
24149  1.0  22.0             0              0             1          4
36098  1.0  22.0             0              0             1          3
6350   1.0  52.0             0              0             1          3
...    ...   ...           ...            ...           ...        ...
9810   0.0  57.0             0              0             1          4
33918  1.0  16.0             0              0             1          4
30678  1.0  13.0             0              0             1          3
18646  1.0  42.0             0              0             1          3
21453  1.0  69.0             0              0             1          4

       Residence_type  avg_glucose_level   bmi  smoking_status
21489               0              76.55  29.0               1
15231               0             104.12  23.5               0
24149               0             237.15  27.7               0
36098               1             234.06  33.7               0
6350                1              99.33  33.7               0
...               ...                ...   ...             ...
9810                1              60.91  29.9               0
33918               1             102.77  35.8               1
30678               1              68.61  31.9               0
18646               0              90.00  32.0               0
21453               1              83.41  29.9               0

[20000 rows x 10 columns]

In [18]:
print(Y)

21489    0
15231    1
24149    0
36098    0
6350     1
        ..
9810     1
33918    0
30678    0
18646    1
21453    0
Name: stroke, Length: 20000, dtype: int64

Train Test Split

In [20]:

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state=2)

In [21]:
print(X.shape, X_train.shape, X_test.shape)
print(Y.shape, Y_train.shape, Y_test.shape)

(20000, 10) (16000, 10) (4000, 10)
(20000,) (16000,) (4000,)

Training the Model

In [23]:
X_train

,sex,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
29922,0.0,32.0,0,0,1,3,0,68.53,29.7,0
40726,0.0,17.0,0,0,1,4,0,95.36,21.5,1
28147,1.0,81.0,0,0,0,4,1,73.50,41.3,1
5320,1.0,66.0,0,1,1,4,1,68.53,24.2,1
22938,1.0,55.0,0,0,1,4,0,83.16,28.3,0
...,...,...,...,...,...,...,...,...,...,...
25790,1.0,17.0,0,0,1,4,1,118.44,24.8,0
23100,0.0,86.0,0,0,1,2,1,71.79,43.0,1
28589,0.0,70.0,0,0,1,2,1,94.24,29.2,1
1711,1.0,18.0,0,0,1,4,1,74.11,20.5,0
37805,1.0,19.0,1,0,1,4,1,93.21,43.8,0

# Model :

In [25]:
from sklearn.linear_model import LogisticRegression
regression = LogisticRegression(random_state = 5,max_iter=300,solver='liblinear')
regression.fit(X_train, Y_train)

LogisticRegression(max_iter=300, random_state=5, solver='liblinear')

In [26]:
prediction = regression.predict(X_test)
prediction

array([0, 1, 0, ..., 0, 1, 1], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, prediction)
print(cm)
accuracy_score(Y_test,prediction)

[[1516  478]
 [ 744 1262]]

0.6945

## Standard Scaler :

In [29]:
X_train

,sex,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
29922,0.0,32.0,0,0,1,3,0,68.53,29.7,0
40726,0.0,17.0,0,0,1,4,0,95.36,21.5,1
28147,1.0,81.0,0,0,0,4,1,73.50,41.3,1
5320,1.0,66.0,0,1,1,4,1,68.53,24.2,1
22938,1.0,55.0,0,0,1,4,0,83.16,28.3,0
...,...,...,...,...,...,...,...,...,...,...
25790,1.0,17.0,0,0,1,4,1,118.44,24.8,0
23100,0.0,86.0,0,0,1,2,1,71.79,43.0,1
28589,0.0,70.0,0,0,1,2,1,94.24,29.2,1
1711,1.0,18.0,0,0,1,4,1,74.11,20.5,0
37805,1.0,19.0,1,0,1,4,1,93.21,43.8,0

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
from sklearn.linear_model import LogisticRegression
regression = LogisticRegression(random_state = 15,max_iter=300,solver='liblinear')
regression.fit(X_train, Y_train)

LogisticRegression(max_iter=300, random_state=15, solver='liblinear')

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, prediction)
print(cm)
accuracy_score(Y_test,prediction)

[[1516  478]
 [ 744 1262]]

0.6945

In [33]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 5)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=5)

In [34]:
y_pred = classifier.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[1980   14]
 [   3 2003]]

0.99575

In [36]:
y_pred

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [37]:
X_train.shape

(16000, 10)

In [38]:
classifier.predict(sc.transform([[1.0,63.0,0,1,1,4,1,228.69,36.3,1]]))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

Making a Predictive System

In [40]:
input_data = (1,63.0,0,1,1,4,1,228.69,36.3,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not stroke')
else:
  print('The person has stroke')

[1]
The person has stroke

Saving the trained model

In [42]:
import pickle

In [43]:
filename = 'stroke_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [44]:
# loading the saved model
loaded_model = pickle.load(open('stroke_model.sav', 'rb'))

In [45]:
input_data = (1,63.0,0,1,1,4,1,228.69,36.3,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not stroke')
else:
  print('The person has stroke')

[1]
The person has stroke

In [46]:
for column in X.columns:
  print(column)

sex
age
hypertension
heart_disease
ever_married
work_type
Residence_type
avg_glucose_level
bmi
smoking_status

In [47]:
# 1.0	28.0	1	0	1	3	0	72.67	28.9	0

In [48]:
stroke_dataset

,sex,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1.0,63.0,0,1,1,4,1,228.69,36.6,1,1
1,1.0,42.0,0,1,1,4,0,105.92,32.5,0,1
2,0.0,61.0,0,0,1,4,1,171.23,34.4,1,1
3,1.0,41.0,1,0,1,3,0,174.12,24.0,0,1
4,1.0,85.0,0,0,1,4,1,186.21,29.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
40905,1.0,38.0,0,0,0,4,1,120.94,29.7,1,0
40906,0.0,53.0,0,0,1,4,0,77.66,40.8,0,0
40907,1.0,32.0,0,0,1,2,0,231.95,33.2,0,0
40908,1.0,42.0,0,0,1,3,0,216.38,34.5,0,0
40909,1.0,35.0,0,0,0,4,0,95.01,28.0,0,0

In [49]:
# 1.0	66.0	0	0	1	4	1	61.32	23.7	1

input_data = (1,66.0,0,0,1,4,1,61.32,23.7,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not stroke')
else:
  print('The person has stroke')

[1]
The person has stroke

In [50]:
# 1.0	42.0	0	1	1	4	0	105.92	32.5	0

In [51]:
input_data = [1.0,42.0,0,1,1,4,0,105.92,32.5,0]

# # changing the input_data to numpy array
# input_data_as_numpy_array = np.asarray(input_data)

# # reshape the array as we are predicting for one instance
# input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict([input_data])
print(prediction)

if (prediction[0] == 0):
  print('The person has not stroke')
else:
  print('The person has stroke')

[1]
The person has stroke

In [52]:
	

input_data = sc.fit_transform([[0.0,53.0,0,0,1,4,0,77.66,40.8,0]])

# # changing the input_data to numpy array
# input_data_as_numpy_array = np.asarray(input_data)

# # # reshape the array as we are predicting for one instance
# input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not stroke')
else:
  print('The person has stroke')

[1]
The person has stroke