Importing the Dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

PIMA Diabetes Dataset

In [4]:
# loading the diabetes dataset to a pandas DataFrame
cKidney_dataset = pd.read_csv('kidney_disease.csv') 
cKidney_dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [5]:
cKidney_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [6]:
cKidney_dataset.dropna(inplace=True)

In [7]:
cKidney_dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,...,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,...,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
14,14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,...,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
20,20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [8]:
cKidney_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              158 non-null    int64
 1   age             158 non-null    float64
 2   bp              158 non-null    float64
 3   sg              158 non-null    float64
 4   al              158 non-null    float64
 5   su              158 non-null    float64
 6   rbc             158 non-null    object
 7   pc              158 non-null    object
 8   pcc             158 non-null    object
 9   ba              158 non-null    object
 10  bgr             158 non-null    float64
 11  bu              158 non-null    float64
 12  sc              158 non-null    float64
 13  sod             158 non-null    float64
 14  pot             158 non-null    float64
 15  hemo            158 non-null    float64
 16  pcv             158 non-null    object
 17  wc              158 non-null    object
 18  rc              158 non-null    object
 19  htn             158 non-null    object
 20  dm              158 non-null    object
 21  cad             158 non-null    object
 22  appet           158 non-null    object
 23  pe              158 non-null    object
 24  ane             158 non-null    object
 25  classification  158 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 33.3+ KB

In [9]:
# printing the first 5 rows of the dataset
cKidney_dataset.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,...,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,...,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
14,14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,...,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
20,20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd

In [10]:
cKidney_dataset.drop('id',axis=1,inplace=True)

In [11]:
# number of rows and Columns in this dataset
cKidney_dataset.shape

(158, 25)

In [12]:
# getting the statistical measures of the data
cKidney_dataset.describe()

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,49.563291,74.050633,1.019873,0.797468,0.253165,131.341772,52.575949,2.188608,138.848101,4.636709,13.687342
std,15.512244,11.175381,0.005499,1.413130,0.813397,64.939832,47.395382,3.077615,7.489421,3.476351,2.882204
min,6.000000,50.000000,1.005000,0.000000,0.000000,70.000000,10.000000,0.400000,111.000000,2.500000,3.100000
25%,39.250000,60.000000,1.020000,0.000000,0.000000,97.000000,26.000000,0.700000,135.000000,3.700000,12.600000
50%,50.500000,80.000000,1.020000,0.000000,0.000000,115.500000,39.500000,1.100000,139.000000,4.500000,14.250000
75%,60.000000,80.000000,1.025000,1.000000,0.000000,131.750000,49.750000,1.600000,144.000000,4.900000,15.775000
max,83.000000,110.000000,1.025000,4.000000,5.000000,490.000000,309.000000,15.200000,150.000000,47.000000,17.800000

In [13]:
cKidney_dataset['classification'].value_counts()

classification
notckd    115
ckd        43
Name: count, dtype: int64

In [14]:
cKidney_dataset.groupby('classification').mean(numeric_only=True)

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
classification,,,,,,,,,,,
ckd,57.279070,80.000000,1.012791,2.930233,0.930233,193.930233,104.930233,5.711628,131.023256,5.506977,9.769767
notckd,46.678261,71.826087,1.022522,0.000000,0.000000,107.939130,33.000000,0.871304,141.773913,4.311304,15.152174

In [15]:
cKidney_dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [16]:
# separating the data and labels
X = cKidney_dataset.drop(columns = 'classification', axis=1)
Y = cKidney_dataset['classification']

In [17]:
print(X)

      age    bp     sg   al   su       rbc        pc         pcc          ba  \
3    48.0  70.0  1.005  4.0  0.0    normal  abnormal     present  notpresent
9    53.0  90.0  1.020  2.0  0.0  abnormal  abnormal     present  notpresent
11   63.0  70.0  1.010  3.0  0.0  abnormal  abnormal     present  notpresent
14   68.0  80.0  1.010  3.0  2.0    normal  abnormal     present     present
20   61.0  80.0  1.015  2.0  0.0  abnormal  abnormal  notpresent  notpresent
..    ...   ...    ...  ...  ...       ...       ...         ...         ...
395  55.0  80.0  1.020  0.0  0.0    normal    normal  notpresent  notpresent
396  42.0  70.0  1.025  0.0  0.0    normal    normal  notpresent  notpresent
397  12.0  80.0  1.020  0.0  0.0    normal    normal  notpresent  notpresent
398  17.0  60.0  1.025  0.0  0.0    normal    normal  notpresent  notpresent
399  58.0  80.0  1.025  0.0  0.0    normal    normal  notpresent  notpresent

       bgr  ...  hemo  pcv     wc   rc  htn   dm  cad appet   pe  ane
3    117.0  ...  11.2   32   6700  3.9  yes   no   no  poor  yes  yes
9     70.0  ...   9.5   29  12100  3.7  yes  yes   no  poor   no  yes
11   380.0  ...  10.8   32   4500  3.8  yes  yes   no  poor  yes   no
14   157.0  ...   5.6   16  11000  2.6  yes  yes  yes  poor  yes   no
20   173.0  ...   7.7   24   9200  3.2  yes  yes  yes  poor  yes  yes
..     ...  ...   ...  ...    ...  ...  ...  ...  ...   ...  ...  ...
395  140.0  ...  15.7   47   6700  4.9   no   no   no  good   no   no
396   75.0  ...  16.5   54   7800  6.2   no   no   no  good   no   no
397  100.0  ...  15.8   49   6600  5.4   no   no   no  good   no   no
398  114.0  ...  14.2   51   7200  5.9   no   no   no  good   no   no
399  131.0  ...  15.8   53   6800  6.1   no   no   no  good   no   no

[158 rows x 24 columns]

In [18]:
print(Y)

3         ckd
9         ckd
11        ckd
14        ckd
20        ckd
        ...
395    notckd
396    notckd
397    notckd
398    notckd
399    notckd
Name: classification, Length: 158, dtype: object

Train Test Split

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [21]:
print(X.shape, X_train.shape, X_test.shape)

(158, 24) (126, 24) (32, 24)

Training the Model

In [23]:
cKidney_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 3 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             158 non-null    float64
 1   bp              158 non-null    float64
 2   sg              158 non-null    float64
 3   al              158 non-null    float64
 4   su              158 non-null    float64
 5   rbc             158 non-null    object
 6   pc              158 non-null    object
 7   pcc             158 non-null    object
 8   ba              158 non-null    object
 9   bgr             158 non-null    float64
 10  bu              158 non-null    float64
 11  sc              158 non-null    float64
 12  sod             158 non-null    float64
 13  pot             158 non-null    float64
 14  hemo            158 non-null    float64
 15  pcv             158 non-null    object
 16  wc              158 non-null    object
 17  rc              158 non-null    object
 18  htn             158 non-null    object
 19  dm              158 non-null    object
 20  cad             158 non-null    object
 21  appet           158 non-null    object
 22  pe              158 non-null    object
 23  ane             158 non-null    object
 24  classification  158 non-null    object
dtypes: float64(11), object(14)
memory usage: 32.1+ KB

In [24]:
classifier = svm.SVC(kernel='linear')

In [25]:

X_train

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
229,59.0,50.0,1.010,3.0,0.0,normal,abnormal,notpresent,notpresent,241.0,...,9.6,31,15700,3.8,no,yes,no,good,yes,no
379,62.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,78.0,...,16.1,50,5400,5.7,no,no,no,good,no,no
382,48.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,16.8,51,6000,6.5,no,no,no,good,no,no
380,59.0,60.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,113.0,...,15.3,54,6500,4.9,no,no,no,good,no,no
298,34.0,60.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,91.0,...,13.5,48,8600,4.9,no,no,no,good,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,33.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,89.0,...,15.0,40,10300,4.8,no,no,no,good,no,no
74,56.0,90.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,129.0,...,9.1,29,6400,3.4,yes,no,no,good,no,no
242,69.0,70.0,1.010,4.0,3.0,normal,abnormal,present,present,214.0,...,9.4,28,11500,3.3,yes,yes,yes,good,yes,yes
256,60.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,14.5,41,10700,5.1,no,no,no,good,no,no
313,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,104.0,...,17.3,52,8200,4.8,no,no,no,good,no,no

In [26]:

cKidney_dataset = pd.get_dummies(cKidney_dataset,columns=['htn','dm','cad','appet','pe','ane'], dtype="int")

In [27]:

# cKidney_dataset.drop('id',axis=1,inplace=True)

In [28]:
cKidney_dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,dm_no,dm_yes,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,1,0,1,0,0,1,0,1,0,1
9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,0,1,1,0,0,1,1,0,0,1
11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,0,1,1,0,0,1,0,1,1,0
14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,0,1,0,1,0,1,0,1,1,0
20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,...,0,1,0,1,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,1,0,1,0,1,0,1,0,1,0
396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,1,0,1,0,1,0,1,0,1,0
397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,1,0,1,0,1,0,1,0,1,0
398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,1,0,1,0,1,0,1,0,1,0
399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,1,0,1,0,1,0,1,0,1,0

In [29]:
from sklearn.preprocessing import LabelEncoder

# Apply label encoding to all string columns in X
le = LabelEncoder()
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = le.fit_transform(X[col])

In [30]:
X = pd.get_dummies(X)

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y = le.fit_transform(Y)

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [33]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [34]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation

Accuracy Score

In [37]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [38]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  1.0

In [39]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [40]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  1.0

In [41]:

cKidney_dataset.replace(["normal","abnormal","present","notpresent"],[0,1,1,0] )

C:\Users\DELL\AppData\Local\Temp\ipykernel_6060\4106027811.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cKidney_dataset.replace(["normal","abnormal","present","notpresent"],[0,1,1,0] )

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,dm_no,dm_yes,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes
3,48.0,70.0,1.005,4.0,0.0,0,1,1,0,117.0,...,1,0,1,0,0,1,0,1,0,1
9,53.0,90.0,1.020,2.0,0.0,1,1,1,0,70.0,...,0,1,1,0,0,1,1,0,0,1
11,63.0,70.0,1.010,3.0,0.0,1,1,1,0,380.0,...,0,1,1,0,0,1,0,1,1,0
14,68.0,80.0,1.010,3.0,2.0,0,1,1,1,157.0,...,0,1,0,1,0,1,0,1,1,0
20,61.0,80.0,1.015,2.0,0.0,1,1,0,0,173.0,...,0,1,0,1,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,0,0,0,0,140.0,...,1,0,1,0,1,0,1,0,1,0
396,42.0,70.0,1.025,0.0,0.0,0,0,0,0,75.0,...,1,0,1,0,1,0,1,0,1,0
397,12.0,80.0,1.020,0.0,0.0,0,0,0,0,100.0,...,1,0,1,0,1,0,1,0,1,0
398,17.0,60.0,1.025,0.0,0.0,0,0,0,0,114.0,...,1,0,1,0,1,0,1,0,1,0
399,58.0,80.0,1.025,0.0,0.0,0,0,0,0,131.0,...,1,0,1,0,1,0,1,0,1,0

In [42]:
X.iloc[1]

age       53.00
bp        90.00
sg         1.02
al         2.00
su         0.00
rbc        0.00
pc         0.00
pcc        1.00
ba         0.00
bgr       70.00
bu       107.00
sc         7.20
sod      114.00
pot        3.70
hemo       9.50
pcv        8.00
wc        11.00
rc        12.00
htn        1.00
dm         1.00
cad        0.00
appet      1.00
pe         0.00
ane        1.00
Name: 9, dtype: float64

Making a Predictive System

In [44]:
input_data = (53.00,90.00,1.02,2.00,0.00,0.00,0.00,1.00,0.00,70.00,107.00,7.20,114.00,3.70,9.50,8.00,11.00,12.00,1.00,1.00,0.00,1.00,0.00,1.00)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not Chronic Kidney')
else:
  print('The person has Chronic Kidney')

[0]
The person has not Chronic Kidney

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

Saving the trained model

In [46]:
import pickle

In [47]:
filename = 'cKidney_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [48]:
# loading the saved model
loaded_model = pickle.load(open('cKidney_model.sav', 'rb'))

In [49]:
input_data = (53,90,1,2,0,0,0,1,0,70,107,7.20,114,3.70,9.50,8,11,12,1,1,0.00,1,0,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not Chronic Kidney')
else:
  print('The person has Chronic Kidney')

[0]
The person has not Chronic Kidney

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [50]:
for column in X.columns:
  print(column)

age
bp
sg
al
su
rbc
pc
pcc
ba
bgr
bu
sc
sod
pot
hemo
pcv
wc
rc
htn
dm
cad
appet
pe
ane

In [95]:
pd.set_option("display.max_columns",None)
X.iloc[1:100]

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
9,53.0,90.0,1.020,2.0,0.0,0,0,1,0,70.0,107.0,7.2,114.0,3.7,9.5,8,11,12,1,1,0,1,0,1
11,63.0,70.0,1.010,3.0,0.0,0,0,1,0,380.0,60.0,2.7,131.0,4.2,10.8,11,25,13,1,1,0,1,1,0
14,68.0,80.0,1.010,3.0,2.0,1,0,1,1,157.0,90.0,4.1,130.0,6.4,5.6,0,8,2,1,1,1,1,1,0
20,61.0,80.0,1.015,2.0,0.0,0,0,0,0,173.0,148.0,3.9,135.0,5.2,7.7,4,63,7,1,1,1,1,1,1
22,48.0,80.0,1.025,4.0,0.0,1,0,0,0,95.0,163.0,7.7,136.0,3.8,9.8,11,44,9,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,58.0,80.0,1.020,0.0,0.0,1,1,0,0,100.0,50.0,1.2,140.0,3.5,14.0,28,42,39,0,0,0,0,0,0
326,47.0,60.0,1.020,0.0,0.0,1,1,0,0,109.0,25.0,1.1,141.0,4.7,15.8,19,57,26,0,0,0,0,0,0
327,30.0,60.0,1.025,0.0,0.0,1,1,0,0,120.0,31.0,0.8,150.0,4.6,13.4,22,6,32,0,0,0,0,0,0
329,33.0,60.0,1.025,0.0,0.0,1,1,0,0,80.0,25.0,0.9,146.0,3.5,14.1,26,52,25,0,0,0,0,0,0
331,59.0,70.0,1.025,0.0,0.0,1,1,0,0,130.0,39.0,0.7,147.0,4.7,13.5,24,42,19,0,0,0,0,0,0