Importing the Dependencies

In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

PIMA Diabetes Dataset

In [7]:
# loading the diabetes dataset to a pandas DataFrame
hyp_dataset = pd.read_csv('hypertension_data.csv') 
hyp_dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,57.0,1.0,3,145,233,1,0,150,0,2.3,0,0,1,1
1,64.0,0.0,2,130,250,0,1,187,0,3.5,0,0,2,1
2,52.0,1.0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,0.0,1,120,236,0,1,178,0,0.8,2,0,2,1
4,66.0,0.0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26078,72.0,0.0,0,138,294,1,1,106,0,1.9,1,3,2,0
26079,60.0,1.0,0,144,200,0,0,126,1,0.9,1,0,3,0
26080,68.0,1.0,0,100,234,0,1,156,0,0.1,2,1,3,0
26081,67.0,1.0,1,154,232,0,0,164,0,0.0,2,1,2,0
26082,67.0,0.0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [9]:
hyp_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26083 entries, 0 to 26082
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       26083 non-null  float64
 1   sex       26058 non-null  float64
 2   cp        26083 non-null  int64
 3   trestbps  26083 non-null  int64
 4   chol      26083 non-null  int64
 5   fbs       26083 non-null  int64
 6   restecg   26083 non-null  int64
 7   thalach   26083 non-null  int64
 8   exang     26083 non-null  int64
 9   oldpeak   26083 non-null  float64
 10  slope     26083 non-null  int64
 11  ca        26083 non-null  int64
 12  thal      26083 non-null  int64
 13  target    26083 non-null  int64
dtypes: float64(3), int64(11)
memory usage: 2.8 MB

In [11]:
hyp_dataset.dropna(inplace=True)

In [13]:
hyp_dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,57.0,1.0,3,145,233,1,0,150,0,2.3,0,0,1,1
1,64.0,0.0,2,130,250,0,1,187,0,3.5,0,0,2,1
2,52.0,1.0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,0.0,1,120,236,0,1,178,0,0.8,2,0,2,1
4,66.0,0.0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26078,72.0,0.0,0,138,294,1,1,106,0,1.9,1,3,2,0
26079,60.0,1.0,0,144,200,0,0,126,1,0.9,1,0,3,0
26080,68.0,1.0,0,100,234,0,1,156,0,0.1,2,1,3,0
26081,67.0,1.0,1,154,232,0,0,164,0,0.0,2,1,2,0
26082,67.0,0.0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [15]:
hyp_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26058 entries, 0 to 26082
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       26058 non-null  float64
 1   sex       26058 non-null  float64
 2   cp        26058 non-null  int64
 3   trestbps  26058 non-null  int64
 4   chol      26058 non-null  int64
 5   fbs       26058 non-null  int64
 6   restecg   26058 non-null  int64
 7   thalach   26058 non-null  int64
 8   exang     26058 non-null  int64
 9   oldpeak   26058 non-null  float64
 10  slope     26058 non-null  int64
 11  ca        26058 non-null  int64
 12  thal      26058 non-null  int64
 13  target    26058 non-null  int64
dtypes: float64(3), int64(11)
memory usage: 3.0 MB

In [17]:
# printing the first 5 rows of the dataset
hyp_dataset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,57.0,1.0,3,145,233,1,0,150,0,2.3,0,0,1,1
1,64.0,0.0,2,130,250,0,1,187,0,3.5,0,0,2,1
2,52.0,1.0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,0.0,1,120,236,0,1,178,0,0.8,2,0,2,1
4,66.0,0.0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [19]:
# number of rows and Columns in this dataset
hyp_dataset.shape

(26058, 14)

In [21]:
# getting the statistical measures of the data
hyp_dataset.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,26058.000000,26058.00000,26058.000000,26058.000000,26058.000000,26058.000000,26058.000000,26058.000000,26058.000000,26058.000000,26058.000000,26058.000000,26058.000000,26058.000000
mean,55.655730,0.50000,0.956635,131.590682,246.286591,0.149896,0.526057,149.643181,0.326886,1.039742,1.399724,0.720623,2.319057,0.547778
std,15.190407,0.50001,1.022467,17.597086,51.651701,0.356977,0.525688,22.865871,0.469084,1.165673,0.616529,1.011317,0.604868,0.497722
min,11.000000,0.00000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,44.000000,0.00000,0.000000,120.000000,211.000000,0.000000,0.000000,133.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,0.50000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,67.000000,1.00000,2.000000,140.000000,275.000000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,98.000000,1.00000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [23]:
hyp_dataset['target'].value_counts()

target
1    14274
0    11784
Name: count, dtype: int64

0 --> Non-hypertension

1 --> hypertension

In [26]:
hyp_dataset.groupby('target').mean()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
target,,,,,,,,,,,,,
0,56.042940,0.5,0.464868,134.465716,251.007977,0.163272,0.446707,139.075866,0.553632,1.602444,1.161405,1.171589,2.557875
1,55.336066,0.5,1.362617,129.217178,242.388819,0.138854,0.591565,158.367101,0.139695,0.575200,1.596469,0.348326,2.121900

In [ ]:
hyp_dataset

In [28]:
# separating the data and labels
X = hyp_dataset.drop(columns = 'target', axis=1)
Y = hyp_dataset['target']

In [30]:
print(X)

        age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      57.0  1.0   3       145   233    1        0      150      0      2.3
1      64.0  0.0   2       130   250    0        1      187      0      3.5
2      52.0  1.0   1       130   204    0        0      172      0      1.4
3      56.0  0.0   1       120   236    0        1      178      0      0.8
4      66.0  0.0   0       120   354    0        1      163      1      0.6
...     ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
26078  72.0  0.0   0       138   294    1        1      106      0      1.9
26079  60.0  1.0   0       144   200    0        0      126      1      0.9
26080  68.0  1.0   0       100   234    0        1      156      0      0.1
26081  67.0  1.0   1       154   232    0        0      164      0      0.0
26082  67.0  0.0   1       130   236    0        0      174      0      0.0

       slope  ca  thal
0          0   0     1
1          0   0     2
2          2   0     2
3          2   0     2
4          2   0     2
...      ...  ..   ...
26078      1   3     2
26079      1   0     3
26080      2   1     3
26081      2   1     2
26082      1   1     2

[26058 rows x 13 columns]

In [32]:
print(Y)

0        1
1        1
2        1
3        1
4        1
        ..
26078    0
26079    0
26080    0
26081    0
26082    0
Name: target, Length: 26058, dtype: int64

Train Test Split

In [35]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [37]:
print(X.shape, X_train.shape, X_test.shape)

(26058, 13) (20846, 13) (5212, 13)

Training the Model

In [40]:
hyp_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26058 entries, 0 to 26082
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       26058 non-null  float64
 1   sex       26058 non-null  float64
 2   cp        26058 non-null  int64
 3   trestbps  26058 non-null  int64
 4   chol      26058 non-null  int64
 5   fbs       26058 non-null  int64
 6   restecg   26058 non-null  int64
 7   thalach   26058 non-null  int64
 8   exang     26058 non-null  int64
 9   oldpeak   26058 non-null  float64
 10  slope     26058 non-null  int64
 11  ca        26058 non-null  int64
 12  thal      26058 non-null  int64
 13  target    26058 non-null  int64
dtypes: float64(3), int64(11)
memory usage: 3.0 MB

In [42]:
classifier = svm.SVC(kernel='linear')

In [44]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation

Accuracy Score

In [54]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [56]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.8463494195529119

In [58]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [60]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.8493860322333078

Making a Predictive System

In [65]:
input_data = (57.0,1.0,3,145,233,1,0,150,0,2.3,0,0,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not Hypertension')
else:
  print('The person has Hypertension')

[1]
The person has Hypertension

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

Saving the trained model

In [68]:
import pickle

In [78]:
filename = 'hyp_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [80]:
# loading the saved model
loaded_model = pickle.load(open('hyp_model.sav', 'rb'))

In [82]:
input_data = (57.0,1.0,3,145,233,1,0,150,0,2.3,0,0,1)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not Hypertension')
else:
  print('The person has Hypertension')

[1]
The person has Hypertension

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [84]:
for column in X.columns:
  print(column)

age
sex
cp
trestbps
chol
fbs
restecg
thalach
exang
oldpeak
slope
ca
thal