Importing the Dependencies

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

PIMA Diabetes Dataset

In [5]:
# loading the diabetes dataset to a pandas DataFrame
lc_dataset = pd.read_csv('lung_cancer_examples.csv') 
lc_dataset

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [6]:
lc_dataset.drop(columns=['Name','Surname'],inplace=True)

In [7]:
# printing the first 5 rows of the dataset
lc_dataset.head()

   Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [8]:
# number of rows and Columns in this dataset
lc_dataset.shape

(59, 5)

In [9]:
# getting the statistical measures of the data
lc_dataset.describe()

             Age     Smokes      AreaQ     Alkhol     Result
count  59.000000  59.000000  59.000000  59.000000  59.000000
mean   42.627119  15.067797   5.203390   3.237288   0.474576
std    16.235230   7.984607   2.461984   2.380517   0.503640
min    18.000000   0.000000   1.000000   0.000000   0.000000
25%    29.000000  10.000000   3.000000   1.000000   0.000000
50%    39.000000  15.000000   5.000000   3.000000   0.000000
75%    55.000000  20.000000   7.500000   5.000000   1.000000
max    77.000000  34.000000  10.000000   8.000000   1.000000

In [10]:
lc_dataset['Result'].value_counts()

Result
0    31
1    28
Name: count, dtype: int64

0 --> Non-lc

1 --> lc

In [12]:
lc_dataset.groupby('Result').mean()

              Age     Smokes     AreaQ    Alkhol
Result
0       32.870968  12.258065  6.935484  1.419355
1       53.428571  18.178571  3.285714  5.250000

In [13]:
# separating the data and labels
X = lc_dataset.drop(columns = 'Result', axis=1)
Y = lc_dataset['Result']

In [14]:
print(X)

    Age  Smokes  AreaQ  Alkhol
0    35       3      5       4
1    27      20      2       5
2    30       0      5       2
3    28       0      8       1
4    68       4      5       6
5    34       0     10       0
6    58      15     10       0
7    22      12      5       2
8    45       2      6       0
9    52      18      4       5
10   33       4      8       0
11   18      10      6       3
12   25       2      5       1
13   28      20      2       8
14   34      25      4       8
15   39      18      8       1
16   42      22      3       5
17   19      12      8       0
18   62       5      4       3
19   73      10      7       6
20   55      15      1       3
21   33       8      8       1
22   22      20      6       2
23   44       5      8       1
24   77       3      2       6
25   21      20      5       3
26   37      15      6       2
27   34      12      8       0
28   55      20      1       4
29   40      20      2       7
30   36      13      5       2
31   56      20      3       3
32   47      15      1       8
33   62      25      3       4
34   26      10      7       2
35   25      20      8       2
36   59      20      3       4
37   62      15      5       5
38   33      25      8       2
39   37      10      5       3
40   50      20      2       4
41   47      12      8       0
42   69      20      5       4
43   63      20      4       5
44   39      15      7       2
45   21      20      8       3
46   31      20      9       4
47   28      10      4       1
48   53      20      6       3
49   62      20      5       6
50   42      12      6       2
51   44      30      1       6
52   26      34      1       8
53   35      20      5       1
54   26      13      6       1
55   77      20      5       4
56   75      15      3       5
57   43      30      3       8
58   51      25      9       0

In [15]:
print(Y)

0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     1
10    0
11    0
12    0
13    1
14    1
15    0
16    1
17    0
18    1
19    1
20    1
21    0
22    0
23    0
24    1
25    0
26    0
27    0
28    1
29    1
30    0
31    1
32    1
33    1
34    0
35    0
36    1
37    1
38    0
39    0
40    1
41    0
42    1
43    1
44    0
45    0
46    0
47    0
48    1
49    1
50    0
51    1
52    1
53    0
54    0
55    1
56    1
57    1
58    0
Name: Result, dtype: int64

Train Test Split

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [18]:
print(X.shape, X_train.shape, X_test.shape)

(59, 4) (47, 4) (12, 4)

Training the Model

In [20]:
classifier = svm.SVC(kernel='linear')

In [21]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation

Accuracy Score

In [24]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [25]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  1.0

In [26]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [27]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  1.0

Making a Predictive System

In [29]:
input_data = (35,3,5,4)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The person has not lungCancer')
else:
  print('The person has lungCancer')

[1]
The person has lungCancer

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

Saving the trained model

In [31]:
import pickle

In [32]:
filename = 'lc_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [33]:
# loading the saved model
loaded_model = pickle.load(open('lc_model.sav', 'rb'))

In [34]:
for column in X.columns:
  print(column)

Age
Smokes
AreaQ
Alkhol